title:       "Home"
description: "Marking time with style, history and reviews."
baseurl:     ""
url:         "https://minutemarkers.com"
theme:       minima
plugins:
  - jekyll-feed

minima:
  
  skin: classic

  nav_pages:
    - about.md
