title:       "MinuteMarkers"
description: "Marking time with style, history, and reviews."
baseurl:     "/minutemarkers"
url:         "https://micheleguglielmetti.github.io"
theme:       minima
plugins:
  - jekyll-feed
# Note: moved post into _posts folder
