title:       "MinuteMarkers"
description: "Marking time with style, history, and reviews."
baseurl:     ""
url:         "https://minutemarkers.com"
theme:       minima
plugins:
  - jekyll-feed
# Note: moved post into _posts folder
